#! /bin/bash -l

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00
#PBS -l mem=8gb
#PBS -m bea
#PBS -M yanfang.guo@vub.be
#PBS -o ./outPBS/cnnTesto$PBS_JOBID.txt
#PBS -e ./errorPBS/cnnTeste$PBS_JOBID.txt

ml load TensorFlow/1.5.0-foss-2017b-Python-3.6.3-CUDA-9.1.85
ml matplotlib/2.1.0-foss-2017b-Python-3.6.3
ml load Keras/2.1.3-foss-2017b-Python-3.6.3
ml load scikit-learn/0.19.1-foss-2017b-Python-3.6.3



echo "perfrom on 10-category classification"

cd $PBS_O_WORKDIR
./data_set_X_y.py
